export interface RadixColor {
  name: string;
  value: string;
  scale: string;
  step: number;
}

export const radixColors: RadixColor[] = [
  // Gray
  { name: "Gray 1", value: "#fcfcfc", scale: "gray", step: 1 },
  { name: "Gray 2", value: "#f9f9f9", scale: "gray", step: 2 },
  { name: "Gray 3", value: "#f0f0f0", scale: "gray", step: 3 },
  { name: "Gray 4", value: "#e8e8e8", scale: "gray", step: 4 },
  { name: "Gray 5", value: "#e0e0e0", scale: "gray", step: 5 },
  { name: "Gray 6", value: "#d9d9d9", scale: "gray", step: 6 },
  { name: "Gray 7", value: "#cecece", scale: "gray", step: 7 },
  { name: "Gray 8", value: "#bbbbbb", scale: "gray", step: 8 },
  { name: "Gray 9", value: "#8d8d8d", scale: "gray", step: 9 },
  { name: "Gray 10", value: "#838383", scale: "gray", step: 10 },
  { name: "Gray 11", value: "#646464", scale: "gray", step: 11 },
  { name: "Gray 12", value: "#202020", scale: "gray", step: 12 },

  // Mauve
  { name: "Mauve 1", value: "#fdfcfd", scale: "mauve", step: 1 },
  { name: "Mauve 2", value: "#faf9fb", scale: "mauve", step: 2 },
  { name: "Mauve 3", value: "#f2eff3", scale: "mauve", step: 3 },
  { name: "Mauve 4", value: "#eae7ec", scale: "mauve", step: 4 },
  { name: "Mauve 5", value: "#e3dfe6", scale: "mauve", step: 5 },
  { name: "Mauve 6", value: "#dbd8e0", scale: "mauve", step: 6 },
  { name: "Mauve 7", value: "#d0cdd7", scale: "mauve", step: 7 },
  { name: "Mauve 8", value: "#bcbac7", scale: "mauve", step: 8 },
  { name: "Mauve 9", value: "#8e8c99", scale: "mauve", step: 9 },
  { name: "Mauve 10", value: "#84828e", scale: "mauve", step: 10 },
  { name: "Mauve 11", value: "#65636d", scale: "mauve", step: 11 },
  { name: "Mauve 12", value: "#211f26", scale: "mauve", step: 12 },

  // Slate
  { name: "Slate 1", value: "#fcfcfd", scale: "slate", step: 1 },
  { name: "Slate 2", value: "#f9f9fb", scale: "slate", step: 2 },
  { name: "Slate 3", value: "#f0f0f3", scale: "slate", step: 3 },
  { name: "Slate 4", value: "#e8e8ec", scale: "slate", step: 4 },
  { name: "Slate 5", value: "#e0e1e6", scale: "slate", step: 5 },
  { name: "Slate 6", value: "#d9d9e0", scale: "slate", step: 6 },
  { name: "Slate 7", value: "#cdced6", scale: "slate", step: 7 },
  { name: "Slate 8", value: "#b9bbc6", scale: "slate", step: 8 },
  { name: "Slate 9", value: "#8b8d98", scale: "slate", step: 9 },
  { name: "Slate 10", value: "#80838d", scale: "slate", step: 10 },
  { name: "Slate 11", value: "#60646c", scale: "slate", step: 11 },
  { name: "Slate 12", value: "#1c2024", scale: "slate", step: 12 },

  // Sage
  { name: "Sage 1", value: "#fbfdfc", scale: "sage", step: 1 },
  { name: "Sage 2", value: "#f7f9f8", scale: "sage", step: 2 },
  { name: "Sage 3", value: "#eef1f0", scale: "sage", step: 3 },
  { name: "Sage 4", value: "#e6e9e8", scale: "sage", step: 4 },
  { name: "Sage 5", value: "#dfe2e0", scale: "sage", step: 5 },
  { name: "Sage 6", value: "#d7dad9", scale: "sage", step: 6 },
  { name: "Sage 7", value: "#cbcfcd", scale: "sage", step: 7 },
  { name: "Sage 8", value: "#b8bcba", scale: "sage", step: 8 },
  { name: "Sage 9", value: "#868e8b", scale: "sage", step: 9 },
  { name: "Sage 10", value: "#7c8481", scale: "sage", step: 10 },
  { name: "Sage 11", value: "#5f6563", scale: "sage", step: 11 },
  { name: "Sage 12", value: "#1a211e", scale: "sage", step: 12 },

  // Olive
  { name: "Olive 1", value: "#fcfdfc", scale: "olive", step: 1 },
  { name: "Olive 2", value: "#f8faf8", scale: "olive", step: 2 },
  { name: "Olive 3", value: "#eff1ef", scale: "olive", step: 3 },
  { name: "Olive 4", value: "#e7e9e7", scale: "olive", step: 4 },
  { name: "Olive 5", value: "#dfe2df", scale: "olive", step: 5 },
  { name: "Olive 6", value: "#d7dad7", scale: "olive", step: 6 },
  { name: "Olive 7", value: "#cccfcc", scale: "olive", step: 7 },
  { name: "Olive 8", value: "#b9bcb8", scale: "olive", step: 8 },
  { name: "Olive 9", value: "#898e87", scale: "olive", step: 9 },
  { name: "Olive 10", value: "#7f847d", scale: "olive", step: 10 },
  { name: "Olive 11", value: "#60655f", scale: "olive", step: 11 },
  { name: "Olive 12", value: "#1d211c", scale: "olive", step: 12 },

  // Sand
  { name: "Sand 1", value: "#fdfdfc", scale: "sand", step: 1 },
  { name: "Sand 2", value: "#f9f9f8", scale: "sand", step: 2 },
  { name: "Sand 3", value: "#f1f0ef", scale: "sand", step: 3 },
  { name: "Sand 4", value: "#e9e8e6", scale: "sand", step: 4 },
  { name: "Sand 5", value: "#e2e1de", scale: "sand", step: 5 },
  { name: "Sand 6", value: "#dad9d6", scale: "sand", step: 6 },
  { name: "Sand 7", value: "#cfceca", scale: "sand", step: 7 },
  { name: "Sand 8", value: "#bcbbb5", scale: "sand", step: 8 },
  { name: "Sand 9", value: "#8d8d86", scale: "sand", step: 9 },
  { name: "Sand 10", value: "#82827c", scale: "sand", step: 10 },
  { name: "Sand 11", value: "#63635e", scale: "sand", step: 11 },
  { name: "Sand 12", value: "#21201c", scale: "sand", step: 12 },

  // Tomato
  { name: "Tomato 1", value: "#fffcfc", scale: "tomato", step: 1 },
  { name: "Tomato 2", value: "#fff8f7", scale: "tomato", step: 2 },
  { name: "Tomato 3", value: "#feebe7", scale: "tomato", step: 3 },
  { name: "Tomato 4", value: "#ffdcd3", scale: "tomato", step: 4 },
  { name: "Tomato 5", value: "#ffcdc2", scale: "tomato", step: 5 },
  { name: "Tomato 6", value: "#fdbdaf", scale: "tomato", step: 6 },
  { name: "Tomato 7", value: "#f5a898", scale: "tomato", step: 7 },
  { name: "Tomato 8", value: "#ec8e7b", scale: "tomato", step: 8 },
  { name: "Tomato 9", value: "#e54d2e", scale: "tomato", step: 9 },
  { name: "Tomato 10", value: "#dd4425", scale: "tomato", step: 10 },
  { name: "Tomato 11", value: "#d13415", scale: "tomato", step: 11 },
  { name: "Tomato 12", value: "#5c271f", scale: "tomato", step: 12 },

  // Red
  { name: "Red 1", value: "#fffcfc", scale: "red", step: 1 },
  { name: "Red 2", value: "#fff7f7", scale: "red", step: 2 },
  { name: "Red 3", value: "#feebec", scale: "red", step: 3 },
  { name: "Red 4", value: "#ffdbdc", scale: "red", step: 4 },
  { name: "Red 5", value: "#ffcdce", scale: "red", step: 5 },
  { name: "Red 6", value: "#fdbdbe", scale: "red", step: 6 },
  { name: "Red 7", value: "#f4a9aa", scale: "red", step: 7 },
  { name: "Red 8", value: "#eb8e90", scale: "red", step: 8 },
  { name: "Red 9", value: "#e5484d", scale: "red", step: 9 },
  { name: "Red 10", value: "#dc3e42", scale: "red", step: 10 },
  { name: "Red 11", value: "#ce2c31", scale: "red", step: 11 },
  { name: "Red 12", value: "#641723", scale: "red", step: 12 },

  // Ruby
  { name: "Ruby 1", value: "#fffcfd", scale: "ruby", step: 1 },
  { name: "Ruby 2", value: "#fff7f8", scale: "ruby", step: 2 },
  { name: "Ruby 3", value: "#feeaed", scale: "ruby", step: 3 },
  { name: "Ruby 4", value: "#ffdce1", scale: "ruby", step: 4 },
  { name: "Ruby 5", value: "#ffced6", scale: "ruby", step: 5 },
  { name: "Ruby 6", value: "#f8bfc8", scale: "ruby", step: 6 },
  { name: "Ruby 7", value: "#efacb8", scale: "ruby", step: 7 },
  { name: "Ruby 8", value: "#e592a3", scale: "ruby", step: 8 },
  { name: "Ruby 9", value: "#e54666", scale: "ruby", step: 9 },
  { name: "Ruby 10", value: "#dc3b5d", scale: "ruby", step: 10 },
  { name: "Ruby 11", value: "#ca244d", scale: "ruby", step: 11 },
  { name: "Ruby 12", value: "#64172b", scale: "ruby", step: 12 },

  // Crimson
  { name: "Crimson 1", value: "#fffcfd", scale: "crimson", step: 1 },
  { name: "Crimson 2", value: "#fef7f9", scale: "crimson", step: 2 },
  { name: "Crimson 3", value: "#ffe9f0", scale: "crimson", step: 3 },
  { name: "Crimson 4", value: "#fedce7", scale: "crimson", step: 4 },
  { name: "Crimson 5", value: "#facedd", scale: "crimson", step: 5 },
  { name: "Crimson 6", value: "#f3bed1", scale: "crimson", step: 6 },
  { name: "Crimson 7", value: "#eaacc3", scale: "crimson", step: 7 },
  { name: "Crimson 8", value: "#e093b2", scale: "crimson", step: 8 },
  { name: "Crimson 9", value: "#e93d82", scale: "crimson", step: 9 },
  { name: "Crimson 10", value: "#df3478", scale: "crimson", step: 10 },
  { name: "Crimson 11", value: "#cb1d63", scale: "crimson", step: 11 },
  { name: "Crimson 12", value: "#621639", scale: "crimson", step: 12 },

  // Pink
  { name: "Pink 1", value: "#fffcfe", scale: "pink", step: 1 },
  { name: "Pink 2", value: "#fef7fb", scale: "pink", step: 2 },
  { name: "Pink 3", value: "#fee9f5", scale: "pink", step: 3 },
  { name: "Pink 4", value: "#fbdcef", scale: "pink", step: 4 },
  { name: "Pink 5", value: "#f6cee7", scale: "pink", step: 5 },
  { name: "Pink 6", value: "#efbfdd", scale: "pink", step: 6 },
  { name: "Pink 7", value: "#e7acd0", scale: "pink", step: 7 },
  { name: "Pink 8", value: "#dd93c2", scale: "pink", step: 8 },
  { name: "Pink 9", value: "#d6409f", scale: "pink", step: 9 },
  { name: "Pink 10", value: "#cf3897", scale: "pink", step: 10 },
  { name: "Pink 11", value: "#c2298a", scale: "pink", step: 11 },
  { name: "Pink 12", value: "#651249", scale: "pink", step: 12 },

  // Plum
  { name: "Plum 1", value: "#fefcff", scale: "plum", step: 1 },
  { name: "Plum 2", value: "#fdf7fd", scale: "plum", step: 2 },
  { name: "Plum 3", value: "#fbebfb", scale: "plum", step: 3 },
  { name: "Plum 4", value: "#f7def8", scale: "plum", step: 4 },
  { name: "Plum 5", value: "#f2d1f3", scale: "plum", step: 5 },
  { name: "Plum 6", value: "#e9c2ec", scale: "plum", step: 6 },
  { name: "Plum 7", value: "#deade3", scale: "plum", step: 7 },
  { name: "Plum 8", value: "#cf91d8", scale: "plum", step: 8 },
  { name: "Plum 9", value: "#ab4aba", scale: "plum", step: 9 },
  { name: "Plum 10", value: "#a144af", scale: "plum", step: 10 },
  { name: "Plum 11", value: "#953ea3", scale: "plum", step: 11 },
  { name: "Plum 12", value: "#53195d", scale: "plum", step: 12 },

  // Purple
  { name: "Purple 1", value: "#fefcfe", scale: "purple", step: 1 },
  { name: "Purple 2", value: "#fbf7fe", scale: "purple", step: 2 },
  { name: "Purple 3", value: "#f7edfe", scale: "purple", step: 3 },
  { name: "Purple 4", value: "#f2e2fc", scale: "purple", step: 4 },
  { name: "Purple 5", value: "#ead5f9", scale: "purple", step: 5 },
  { name: "Purple 6", value: "#e0c4f4", scale: "purple", step: 6 },
  { name: "Purple 7", value: "#d1afec", scale: "purple", step: 7 },
  { name: "Purple 8", value: "#be93e4", scale: "purple", step: 8 },
  { name: "Purple 9", value: "#8e4ec6", scale: "purple", step: 9 },
  { name: "Purple 10", value: "#8347b9", scale: "purple", step: 10 },
  { name: "Purple 11", value: "#8145b5", scale: "purple", step: 11 },
  { name: "Purple 12", value: "#402060", scale: "purple", step: 12 },

  // Violet
  { name: "Violet 1", value: "#fdfcfe", scale: "violet", step: 1 },
  { name: "Violet 2", value: "#faf8ff", scale: "violet", step: 2 },
  { name: "Violet 3", value: "#f4f0fe", scale: "violet", step: 3 },
  { name: "Violet 4", value: "#ebe4ff", scale: "violet", step: 4 },
  { name: "Violet 5", value: "#e1d9ff", scale: "violet", step: 5 },
  { name: "Violet 6", value: "#d4cafe", scale: "violet", step: 6 },
  { name: "Violet 7", value: "#c2b5f5", scale: "violet", step: 7 },
  { name: "Violet 8", value: "#aa99ec", scale: "violet", step: 8 },
  { name: "Violet 9", value: "#6e56cf", scale: "violet", step: 9 },
  { name: "Violet 10", value: "#654dc4", scale: "violet", step: 10 },
  { name: "Violet 11", value: "#6550b9", scale: "violet", step: 11 },
  { name: "Violet 12", value: "#2f265f", scale: "violet", step: 12 },

  // Iris
  { name: "Iris 1", value: "#fdfdff", scale: "iris", step: 1 },
  { name: "Iris 2", value: "#f8f8ff", scale: "iris", step: 2 },
  { name: "Iris 3", value: "#f0f1fe", scale: "iris", step: 3 },
  { name: "Iris 4", value: "#e6e7ff", scale: "iris", step: 4 },
  { name: "Iris 5", value: "#dadcff", scale: "iris", step: 5 },
  { name: "Iris 6", value: "#cbcdff", scale: "iris", step: 6 },
  { name: "Iris 7", value: "#b8baf8", scale: "iris", step: 7 },
  { name: "Iris 8", value: "#9b9ef0", scale: "iris", step: 8 },
  { name: "Iris 9", value: "#5b5bd6", scale: "iris", step: 9 },
  { name: "Iris 10", value: "#5151cd", scale: "iris", step: 10 },
  { name: "Iris 11", value: "#5753c6", scale: "iris", step: 11 },
  { name: "Iris 12", value: "#272962", scale: "iris", step: 12 },

  // Indigo
  { name: "Indigo 1", value: "#fdfdfe", scale: "indigo", step: 1 },
  { name: "Indigo 2", value: "#f7f9ff", scale: "indigo", step: 2 },
  { name: "Indigo 3", value: "#edf2fe", scale: "indigo", step: 3 },
  { name: "Indigo 4", value: "#e1e9ff", scale: "indigo", step: 4 },
  { name: "Indigo 5", value: "#d2deff", scale: "indigo", step: 5 },
  { name: "Indigo 6", value: "#c1d0ff", scale: "indigo", step: 6 },
  { name: "Indigo 7", value: "#abbdf9", scale: "indigo", step: 7 },
  { name: "Indigo 8", value: "#8da4ef", scale: "indigo", step: 8 },
  { name: "Indigo 9", value: "#3e63dd", scale: "indigo", step: 9 },
  { name: "Indigo 10", value: "#3358d4", scale: "indigo", step: 10 },
  { name: "Indigo 11", value: "#3a5bc7", scale: "indigo", step: 11 },
  { name: "Indigo 12", value: "#1f2d5c", scale: "indigo", step: 12 },

  // Blue
  { name: "Blue 1", value: "#fbfdff", scale: "blue", step: 1 },
  { name: "Blue 2", value: "#f4faff", scale: "blue", step: 2 },
  { name: "Blue 3", value: "#e6f4fe", scale: "blue", step: 3 },
  { name: "Blue 4", value: "#d5efff", scale: "blue", step: 4 },
  { name: "Blue 5", value: "#c2e5ff", scale: "blue", step: 5 },
  { name: "Blue 6", value: "#acd8fc", scale: "blue", step: 6 },
  { name: "Blue 7", value: "#8ec8f6", scale: "blue", step: 7 },
  { name: "Blue 8", value: "#5eb1ef", scale: "blue", step: 8 },
  { name: "Blue 9", value: "#0090ff", scale: "blue", step: 9 },
  { name: "Blue 10", value: "#0588f0", scale: "blue", step: 10 },
  { name: "Blue 11", value: "#0d74ce", scale: "blue", step: 11 },
  { name: "Blue 12", value: "#113264", scale: "blue", step: 12 },

  // Cyan
  { name: "Cyan 1", value: "#fafdfe", scale: "cyan", step: 1 },
  { name: "Cyan 2", value: "#f2fafb", scale: "cyan", step: 2 },
  { name: "Cyan 3", value: "#def7f9", scale: "cyan", step: 3 },
  { name: "Cyan 4", value: "#caf1f6", scale: "cyan", step: 4 },
  { name: "Cyan 5", value: "#b5e9f0", scale: "cyan", step: 5 },
  { name: "Cyan 6", value: "#9ddde7", scale: "cyan", step: 6 },
  { name: "Cyan 7", value: "#7dcedc", scale: "cyan", step: 7 },
  { name: "Cyan 8", value: "#3db9cf", scale: "cyan", step: 8 },
  { name: "Cyan 9", value: "#00a2c7", scale: "cyan", step: 9 },
  { name: "Cyan 10", value: "#0797b9", scale: "cyan", step: 10 },
  { name: "Cyan 11", value: "#107d98", scale: "cyan", step: 11 },
  { name: "Cyan 12", value: "#0d3c48", scale: "cyan", step: 12 },

  // Teal
  { name: "Teal 1", value: "#fafefd", scale: "teal", step: 1 },
  { name: "Teal 2", value: "#f3fbf9", scale: "teal", step: 2 },
  { name: "Teal 3", value: "#e0f8f3", scale: "teal", step: 3 },
  { name: "Teal 4", value: "#ccf3ea", scale: "teal", step: 4 },
  { name: "Teal 5", value: "#b8eae0", scale: "teal", step: 5 },
  { name: "Teal 6", value: "#a1ded2", scale: "teal", step: 6 },
  { name: "Teal 7", value: "#83cdc1", scale: "teal", step: 7 },
  { name: "Teal 8", value: "#53b9ab", scale: "teal", step: 8 },
  { name: "Teal 9", value: "#12a594", scale: "teal", step: 9 },
  { name: "Teal 10", value: "#0d9b8a", scale: "teal", step: 10 },
  { name: "Teal 11", value: "#008573", scale: "teal", step: 11 },
  { name: "Teal 12", value: "#0d3d38", scale: "teal", step: 12 },

  // Jade
  { name: "Jade 1", value: "#fbfefd", scale: "jade", step: 1 },
  { name: "Jade 2", value: "#f4fbf7", scale: "jade", step: 2 },
  { name: "Jade 3", value: "#e6f7ed", scale: "jade", step: 3 },
  { name: "Jade 4", value: "#d6f1e3", scale: "jade", step: 4 },
  { name: "Jade 5", value: "#c3e9d7", scale: "jade", step: 5 },
  { name: "Jade 6", value: "#acdec8", scale: "jade", step: 6 },
  { name: "Jade 7", value: "#8bceb6", scale: "jade", step: 7 },
  { name: "Jade 8", value: "#56ba9f", scale: "jade", step: 8 },
  { name: "Jade 9", value: "#29a383", scale: "jade", step: 9 },
  { name: "Jade 10", value: "#26997b", scale: "jade", step: 10 },
  { name: "Jade 11", value: "#208368", scale: "jade", step: 11 },
  { name: "Jade 12", value: "#1d3b31", scale: "jade", step: 12 },

  // Green
  { name: "Green 1", value: "#fbfefc", scale: "green", step: 1 },
  { name: "Green 2", value: "#f4fbf6", scale: "green", step: 2 },
  { name: "Green 3", value: "#e6f6eb", scale: "green", step: 3 },
  { name: "Green 4", value: "#d6f1df", scale: "green", step: 4 },
  { name: "Green 5", value: "#c4e8d1", scale: "green", step: 5 },
  { name: "Green 6", value: "#adddc0", scale: "green", step: 6 },
  { name: "Green 7", value: "#8eceaa", scale: "green", step: 7 },
  { name: "Green 8", value: "#5bb98b", scale: "green", step: 8 },
  { name: "Green 9", value: "#30a46c", scale: "green", step: 9 },
  { name: "Green 10", value: "#2b9a66", scale: "green", step: 10 },
  { name: "Green 11", value: "#218358", scale: "green", step: 11 },
  { name: "Green 12", value: "#193b2d", scale: "green", step: 12 },

  // Grass
  { name: "Grass 1", value: "#fbfefb", scale: "grass", step: 1 },
  { name: "Grass 2", value: "#f5fbf5", scale: "grass", step: 2 },
  { name: "Grass 3", value: "#e9f6e9", scale: "grass", step: 3 },
  { name: "Grass 4", value: "#daf1db", scale: "grass", step: 4 },
  { name: "Grass 5", value: "#c9e8ca", scale: "grass", step: 5 },
  { name: "Grass 6", value: "#b2ddb5", scale: "grass", step: 6 },
  { name: "Grass 7", value: "#94ce9a", scale: "grass", step: 7 },
  { name: "Grass 8", value: "#65ba74", scale: "grass", step: 8 },
  { name: "Grass 9", value: "#46a758", scale: "grass", step: 9 },
  { name: "Grass 10", value: "#3e9b4f", scale: "grass", step: 10 },
  { name: "Grass 11", value: "#2a7e3b", scale: "grass", step: 11 },
  { name: "Grass 12", value: "#203c25", scale: "grass", step: 12 },

  // Brown
  { name: "Brown 1", value: "#fefdfc", scale: "brown", step: 1 },
  { name: "Brown 2", value: "#fcf9f6", scale: "brown", step: 2 },
  { name: "Brown 3", value: "#f6eee7", scale: "brown", step: 3 },
  { name: "Brown 4", value: "#f0e4d9", scale: "brown", step: 4 },
  { name: "Brown 5", value: "#ebdaca", scale: "brown", step: 5 },
  { name: "Brown 6", value: "#e4cdb7", scale: "brown", step: 6 },
  { name: "Brown 7", value: "#dcbc9f", scale: "brown", step: 7 },
  { name: "Brown 8", value: "#cea37e", scale: "brown", step: 8 },
  { name: "Brown 9", value: "#ad7f58", scale: "brown", step: 9 },
  { name: "Brown 10", value: "#a07553", scale: "brown", step: 10 },
  { name: "Brown 11", value: "#815e46", scale: "brown", step: 11 },
  { name: "Brown 12", value: "#3e332e", scale: "brown", step: 12 },

  // Bronze
  { name: "Bronze 1", value: "#fdfcfc", scale: "bronze", step: 1 },
  { name: "Bronze 2", value: "#fdf7f5", scale: "bronze", step: 2 },
  { name: "Bronze 3", value: "#f6edea", scale: "bronze", step: 3 },
  { name: "Bronze 4", value: "#efe4df", scale: "bronze", step: 4 },
  { name: "Bronze 5", value: "#e7d9d3", scale: "bronze", step: 5 },
  { name: "Bronze 6", value: "#dfcdc5", scale: "bronze", step: 6 },
  { name: "Bronze 7", value: "#d3bcb3", scale: "bronze", step: 7 },
  { name: "Bronze 8", value: "#c2a499", scale: "bronze", step: 8 },
  { name: "Bronze 9", value: "#a18072", scale: "bronze", step: 9 },
  { name: "Bronze 10", value: "#957468", scale: "bronze", step: 10 },
  { name: "Bronze 11", value: "#7d5e54", scale: "bronze", step: 11 },
  { name: "Bronze 12", value: "#43302b", scale: "bronze", step: 12 },

  // Gold
  { name: "Gold 1", value: "#fdfdfc", scale: "gold", step: 1 },
  { name: "Gold 2", value: "#faf9f2", scale: "gold", step: 2 },
  { name: "Gold 3", value: "#f2f0e7", scale: "gold", step: 3 },
  { name: "Gold 4", value: "#eae6db", scale: "gold", step: 4 },
  { name: "Gold 5", value: "#e1dccf", scale: "gold", step: 5 },
  { name: "Gold 6", value: "#d8d0bf", scale: "gold", step: 6 },
  { name: "Gold 7", value: "#cbc0aa", scale: "gold", step: 7 },
  { name: "Gold 8", value: "#b9a88d", scale: "gold", step: 8 },
  { name: "Gold 9", value: "#978365", scale: "gold", step: 9 },
  { name: "Gold 10", value: "#8c7a5e", scale: "gold", step: 10 },
  { name: "Gold 11", value: "#71624b", scale: "gold", step: 11 },
  { name: "Gold 12", value: "#3b352b", scale: "gold", step: 12 },

  // Sky
  { name: "Sky 1", value: "#f9feff", scale: "sky", step: 1 },
  { name: "Sky 2", value: "#f1fafd", scale: "sky", step: 2 },
  { name: "Sky 3", value: "#e1f6fd", scale: "sky", step: 3 },
  { name: "Sky 4", value: "#d1f0fa", scale: "sky", step: 4 },
  { name: "Sky 5", value: "#bee7f5", scale: "sky", step: 5 },
  { name: "Sky 6", value: "#a9daed", scale: "sky", step: 6 },
  { name: "Sky 7", value: "#8dcae3", scale: "sky", step: 7 },
  { name: "Sky 8", value: "#60b3d7", scale: "sky", step: 8 },
  { name: "Sky 9", value: "#7ce2fe", scale: "sky", step: 9 },
  { name: "Sky 10", value: "#74daf8", scale: "sky", step: 10 },
  { name: "Sky 11", value: "#00749e", scale: "sky", step: 11 },
  { name: "Sky 12", value: "#1d3e56", scale: "sky", step: 12 },

  // Mint
  { name: "Mint 1", value: "#f9fefd", scale: "mint", step: 1 },
  { name: "Mint 2", value: "#f2fbf9", scale: "mint", step: 2 },
  { name: "Mint 3", value: "#ddf9f2", scale: "mint", step: 3 },
  { name: "Mint 4", value: "#c8f4e9", scale: "mint", step: 4 },
  { name: "Mint 5", value: "#b3ecde", scale: "mint", step: 5 },
  { name: "Mint 6", value: "#9ce0d0", scale: "mint", step: 6 },
  { name: "Mint 7", value: "#7ecfbd", scale: "mint", step: 7 },
  { name: "Mint 8", value: "#4cbba5", scale: "mint", step: 8 },
  { name: "Mint 9", value: "#86ead4", scale: "mint", step: 9 },
  { name: "Mint 10", value: "#7de0cb", scale: "mint", step: 10 },
  { name: "Mint 11", value: "#027864", scale: "mint", step: 11 },
  { name: "Mint 12", value: "#16433c", scale: "mint", step: 12 },

  // Lime
  { name: "Lime 1", value: "#fcfdfa", scale: "lime", step: 1 },
  { name: "Lime 2", value: "#f8faf3", scale: "lime", step: 2 },
  { name: "Lime 3", value: "#eef6d6", scale: "lime", step: 3 },
  { name: "Lime 4", value: "#e2f0bd", scale: "lime", step: 4 },
  { name: "Lime 5", value: "#d3e7a6", scale: "lime", step: 5 },
  { name: "Lime 6", value: "#c2da91", scale: "lime", step: 6 },
  { name: "Lime 7", value: "#abc978", scale: "lime", step: 7 },
  { name: "Lime 8", value: "#8db654", scale: "lime", step: 8 },
  { name: "Lime 9", value: "#bdee63", scale: "lime", step: 9 },
  { name: "Lime 10", value: "#b0e64c", scale: "lime", step: 10 },
  { name: "Lime 11", value: "#5c7c2f", scale: "lime", step: 11 },
  { name: "Lime 12", value: "#37401c", scale: "lime", step: 12 },

  // Yellow
  { name: "Yellow 1", value: "#fdfdf9", scale: "yellow", step: 1 },
  { name: "Yellow 2", value: "#fefce9", scale: "yellow", step: 2 },
  { name: "Yellow 3", value: "#fffab8", scale: "yellow", step: 3 },
  { name: "Yellow 4", value: "#fff394", scale: "yellow", step: 4 },
  { name: "Yellow 5", value: "#ffe770", scale: "yellow", step: 5 },
  { name: "Yellow 6", value: "#f3d768", scale: "yellow", step: 6 },
  { name: "Yellow 7", value: "#e4c767", scale: "yellow", step: 7 },
  { name: "Yellow 8", value: "#d5ae39", scale: "yellow", step: 8 },
  { name: "Yellow 9", value: "#ffe629", scale: "yellow", step: 9 },
  { name: "Yellow 10", value: "#ffdc00", scale: "yellow", step: 10 },
  { name: "Yellow 11", value: "#9e6c00", scale: "yellow", step: 11 },
  { name: "Yellow 12", value: "#473b1f", scale: "yellow", step: 12 },

  // Amber
  { name: "Amber 1", value: "#fefdfb", scale: "amber", step: 1 },
  { name: "Amber 2", value: "#fefbe9", scale: "amber", step: 2 },
  { name: "Amber 3", value: "#fff7c2", scale: "amber", step: 3 },
  { name: "Amber 4", value: "#ffee9c", scale: "amber", step: 4 },
  { name: "Amber 5", value: "#fbe577", scale: "amber", step: 5 },
  { name: "Amber 6", value: "#f3d673", scale: "amber", step: 6 },
  { name: "Amber 7", value: "#e9c162", scale: "amber", step: 7 },
  { name: "Amber 8", value: "#e2a336", scale: "amber", step: 8 },
  { name: "Amber 9", value: "#ffc53d", scale: "amber", step: 9 },
  { name: "Amber 10", value: "#ffba18", scale: "amber", step: 10 },
  { name: "Amber 11", value: "#ab6400", scale: "amber", step: 11 },
  { name: "Amber 12", value: "#4f3422", scale: "amber", step: 12 },

  // Orange
  { name: "Orange 1", value: "#fefcfb", scale: "orange", step: 1 },
  { name: "Orange 2", value: "#fff7ed", scale: "orange", step: 2 },
  { name: "Orange 3", value: "#ffefd6", scale: "orange", step: 3 },
  { name: "Orange 4", value: "#ffdfb5", scale: "orange", step: 4 },
  { name: "Orange 5", value: "#ffd19a", scale: "orange", step: 5 },
  { name: "Orange 6", value: "#ffc182", scale: "orange", step: 6 },
  { name: "Orange 7", value: "#f5ae73", scale: "orange", step: 7 },
  { name: "Orange 8", value: "#ec9455", scale: "orange", step: 8 },
  { name: "Orange 9", value: "#f76b15", scale: "orange", step: 9 },
  { name: "Orange 10", value: "#ef5f00", scale: "orange", step: 10 },
  { name: "Orange 11", value: "#cc4e00", scale: "orange", step: 11 },
  { name: "Orange 12", value: "#582d1d", scale: "orange", step: 12 }
];